### ISSUE TITLE
Make a utility taking systems into AMBER/GROMACS

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#184]
Make a utility or example which will take SMIRFF system and go to AMBER `prmtop` and `crd` and/or GROMACS `top` and `gro`, as per https://github.com/choderalab/yank/issues/544#issuecomment-262032469

I can rely on github.com/mobleylab/solvationtoolkit for system prep, so really this means just taking a system which is already prepped (`.pdb` and `.mol2` files for the system and components available), parameterizing with SMIRFF, and going into GROMACS or AMBER format. Since the conversion from OpenMM to AMBER/GROMACS can be handled by `ParmEd`, I think this should be fairly trivial.

**Comment by jchodera** [comment]
Do we want to use TIP3P water or parm@frosst water? And would we want to use Amber or SMIRFF formats for the water?

You'll want to include as input:
* PDB file for the system to read in Topology and positions
* Mol2 files with partial charges for small molecule and solcent (if parameterizing solvent box)

I would save the serialized OpenMM System XML as well, just in case that is useful.

**Comment by davidlmobley** [comment]
@jchodera - how would I save the serialized OpenMM System XML? Am not familiar with that.

Without some new development, I think we can only do AlkEthOH flexible water if we take the whole system from SMIRFF. We don't have constraints yet, nor do we have TIP3P in SMIRFF.

Potentially I could figure out how to do a SMIRFF solute in conventional TIP3P if I bring in TIP3P from AMBER (which would also allow for constraints), though this will take me longer. As a first pass implementation I plan to just provide a way to take an arbitrary all-SMIRFF system into AMBER and GROMACS.

**Comment by jchodera** [comment]
Actually, I wonder if we can easily graft in a reader for OpenMM XML and PDB (much like the amber or Gromacs readers)  so you can skip the ParmEd step. Let me ask @andrrizzi in the morning.

**Comment by jchodera** [comment]
> @jchodera - how would I save the serialized OpenMM System XML? Am not familiar with that.

```python
# serialize system to a string
from simtk.openmm import XmlSerializer
serialized_system = XmlSerializer.serialize(system)
# now write that string to a file
```

> Without some new development, I think we can only do AlkEthOH flexible water if we take the whole system from SMIRFF. We don't have constraints yet, nor do we have TIP3P in SMIRFF.

We can probably easily add constraints. Did that make it into the spec, or
is there just an issue?

We could also encode TIP3P water in SMIRFF if we wanted to use that instead.

> Potentially I could figure out how to do a SMIRFF solute in conventional TIP3P if I bring in TIP3P from AMBER (which would also allow for constraints), though this will take me longer. As a first pass implementation I plan to just provide a way to take an arbitrary all-SMIRFF system into AMBER and GROMACS.

Sounds good. I'd focus on the first part (prior to ParmEd) in case we can
add that XML reader input.

On the other hand, it may be useful to the paper how you can use SMIRFF in
Gromacs or Amber, so that conversion could be valuable.

**Comment by davidlmobley** [comment]
> We could also encode TIP3P water in SMIRFF if we wanted to use that instead.

Yes, that's a good point. The major issue is just the constraints.

I'll go ahead with the converter generally as this is something we need for other reasons, aside from just Yank.

**Comment by andrrizzi** [comment]
> I wonder if we can easily graft in a reader for OpenMM XML and PDB (much like the amber or Gromacs readers) so you can skip the ParmEd step

Sorry for the late response! Yes, that's something that could be implemented in a day or two.

**Comment by davidlmobley** [comment]
Willing to do so soon?  That would help a ton and allow things to be much less amber centric.

**Comment by andrrizzi** [comment]
Ok! I'll do my best to get it in by the end of the week.

**Comment by andrrizzi** [comment]
Not sure if you received the notification via email @davidlmobley, but I've added the feature to support XML systems.

**Comment by davidlmobley** [comment]
I did, @andrrizzi ! I have it on my short list to review. However, I've not used Yank at all yet, so it may take me a bit to figure out how to do this. What would help a lot would be if you could point me something that would show how to take a prepared system (i.e. via this support) and do a hydration calculation. Do you have an example? Even an implicit solvent hydration calculation would be a good start, though I'd also want to do explicit. THat would certainly expedite my review. :) 

Thanks.

**Comment by andrrizzi** [comment]
Of course! No pressure, I just wanted to be sure that you knew.

@Lnaden has written some [great tutorials](http://getyank.org/latest/examples/index.html) that explain in details the examples in the [yank-example repo](https://github.com/choderalab/yank-examples/). That includes hydration free energy examples from SMILES and a `mol2` file, and it's a great place to get the general idea. Unfortunately, we don't have examples documentation yet for specifically setting up a calculation from system files (rather than molecules files that go through the automatic pipeline), but this is how the script would look like:
```yaml
---
options:
  minimize: yes
  verbose: yes
  number_of_iterations: 1000
  temperature: 300*kelvin
  pressure: 1*atmosphere

systems:
  smarty-system:
    phase1_path: [solventsystem.pdb, solventsystem.xml]
    phase2_path: [vacuumsystem.pdb, vacuumsystem.xml]
    ligand_dsl: resname MOL

protocols:
  hydration-protocol:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]

experiments:
  system: smarty-system
  protocol: hydration-protocol
```
